INSERT INTO `sommen` (`inleiding`, `vraag`, `voor_achter`, `eenheid`, `categorie`, `moeilijkheidsgraad`, `antwoord`, `afbeelding`) VALUES
('In 2021 heeft NikeDas 16% meer omzet gedraaid dan in 2020; in 2020 bedroeg de omzet € 3,5 miljoen.',
'Wat is de omzet van NikeDas in 2021?', 0, '€', 0, 0, '4060000', ''),
('Een beer kost zonder korting € 8,55.', 'Wat kost de beer met 12% korting?', 0, '€', 0, 0, '7,52', ''),
('Een Tesla kost € 72.562 maar daar komt de BTW van 21% nog overheen.',
'Hoeveel moet je betalen voor zo’n Tesla? Rond af op hele euro’s.', 0, '€', 0, 0, '87800', ''),
('MediaBlue heeft een aanbieding: voor een laptop van € 765,99 (incl. BTW) krijg je de BTW van 21% terug.',
'Hoeveel kost de laptop je?', 0, '€', 0, 0, '633,05', ''),
('Bij CoolMarkt geldt deze week de aanbieding: 5 WiFi-repeaters halen, 4 betalen. 1 WiFi-repeater kost € 22,64.',
'Hoeveel % korting krijg je dan eigenlijk?', 1, '%', 0, 0, '20', ''),
('Beppe Osinga is sinds dat ze 56 jaar werd, 0,7 mm per jaar gekrompen en ze is nu 84 jaar. Op haar 56ste was ze 1 meter en 89 cm.',
'Met hoeveel % is ze gekrompen de afgelopen jaren sinds haar 56ste? Rond af op 2 decimalen.', 1, '%', 0, 0, '1,04', ''),
('In 2020 was de melkopbrengst per dag van koe Idske_313 zo’n 24,7 liter; Idske_313 droogt langzaam op, ze geeft nu nog 23,1 liter per dag.',
'Met hoeveel procent is de dagelijkse melkopbrengst gedaald? Rond af op 1 decimaal.', 1, '%', 0, 0, '6,5', ''),
('De transferwaarde van de bekende voetballer Mionel Lessi nam in 2019 toe met 75% tot een bedrag van 135 miljoen euro.',
'Wat was zijn transferwaarde voor die tijd? Rond af op duizendtallen.', 0, '€', 0, 0, '77143000', ''),
('Danny heeft een eigen kroeg en verkoopt een pintje voor € 1,90. Op een avond verkoopt Danny 140 pintjes. Danny behaalt die avond met de verkoop van alle producten in totaal een winst van 350 euro.',
'Hoeveel procent van zijn winst behaalde Danny met de verkoop van pintjes? Rond af op 1 decimaal.', 1, '%', 0, 1, '6,8', 'pintje.jpg'),
('Zie afbeelding.', 'Hoeveel procent van de totale Nederlandse bijstandsuitkeringen werd uitgekeerd in Amsterdam en Rotterdam samen? Rond je antwoord af op 1 decimaal.',
1, '%', 0, 0, '20,4', 'bijstandsuitkeringen.jpg'),
('Hassan koopt deze week Minecraft en Halo 5. Voor Minecraft betaalt hij €42 en voor Halo 5 betaalt hij €31.',
'Hoeveel had Hassan in totaal moeten betalen exclusief korting?', 0, '€', 0, 0, '130', 'games.jpg'),
('Wat is de Lelylijn precies? Dat is nog niet precies duidelijk. Voor veel mensen,is het alleen een nieuwe, snelle spoorlijn tussen Lelystad en Groningen. Die halveert de reistijd Groningen - Amsterdam/Schiphol tot ongeveer één uur omdat de afstand korter is dan via Zwolle en de trein harder rijdt: 200 in plaats van 140 tot 160 km per uur. Friesland wil vanaf Heerenveen ook een snelle aftakking naar Leeuwarden.
','Als een oude trein 140 snelheid heeft, hoeveel procent ben jij dan sneller?',0,'%',0,0,'30',''),
('Oude prijs van 320gram Amici tapas schotel was 8.95 euro en nieuwe prijs is 6.95 euro','Met hoeveel procent is prijs gedaalt ?',0,'%',0,0,'22',''),
('Martijn Schoolenberg Op 4 maart van dit jaar wordt de 84-jarige tante van Tom de Jong in de val gelokt. Een ‘medewerker van haar bank’ belt met de mededeling dat er met haar bankpas is gefraudeerd en dat die omgeruild moet worden. Als de alleenstaande vrouw haar adres in Soest geeft, komt er een persoon aan de deur. Hij haalt haar bankpas op en zegt dat het voor het proces ook nodig is dat ze de pincode geeft. Even later is er 1200,38 euro van haar rekening afgeschreven. In 2022 bedroeg de schade in Nederland als gevolg van bankhelp-deskoplichting 51 miljoen euro. Een jaar eerder ging het nog om 47,5 miljoen euro. ',
'hoeveel percentage is het opgelichte geld van oma op de stijging van dit jaar?',0,'%',0,0,'0,03429657143','')